name: J2MC_Harass
main: to.joe.j2mc.harass.J2MC_Harass
version: 1.0
website: http://forums.joe.to
author: J2 Minecraft Plugin Team
description: Harassment module.
commands:
  harass:
    description: Harasses player, toggle based.
    usage: /harass player
    permission: j2mc.harass.harass
    permission-message: No u
  slay:
    description: Slays player
    usage: /slay player
    permission: j2mc.harass.slay
    permission-message: No u
  slap:
    description: Slaps player with specified force
    usage: /slap player force
    permission: j2mc.harass.slap
    permission-message: No u
  smite:
    description: Strikes player down with lightning
    usage:  /smite player
    permission: j2mc.harass.smite
    permission-message: No u
  woof:
    description: Woof
    usage: /woof player
    permission: j2mc.harass.woof
    permission-message: No u
permissions:
  j2mc.harass.slap:
    description: gives access to /slap
  j2mc.harass.slay:
    description: gives access to /slay
  j2mc.harass.smite:
    description: gives access to /smite
  j2mc.harass.abuse:
    description: gives access to /harass
  j2mc.harass.woof:
    description: gives access to /woof
  j2mc.harass.admin:
    description: the big shabang
    children:
      j2mc.harass.harass: true
      j2mc.harass.slap: true
      j2mc.harass.slay: true
      j2mc.harass.smite: true
      j2mc.harass.abuse: true
      j2mc.harass.woof: true