name: J2MC_Harass
main: to.joe.j2mc.harass.J2MC_Harass
version: 0.0prealpha
website: http://forums.joe.to
author: J2 Minecraft Plugin Team
description: Harassment module.
commands:
  harass:
    description: Harrases player, toggle based.
    usage: |
            /harass player
  slay:
    description: Slays player
    usage: |
            /slay player
  slap:
    description: Slaps player with specified force
    usage: |
            /slap player force
  smite:
    description: Strikes player down with lightning
    usage: |
            /smite player